apiVersion: v1
kind: Service
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  ports:
    - port: 8761
  selector:
    app: discovery
  type: LoadBalancer
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: discovery
  labels:
    app: discovery
spec:
  selector:
    matchLabels:
      app: discovery
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: discovery
    spec:
      containers:
        - image: springshop/discovery:latest
          name: discovery
#          env:
#            - name: WORDPRESS_DB_HOST
#              value: mysql
#            - name: WORDPRESS_DB_PASSWORD
#              value: password
          ports:
            - containerPort: 8761
              name: eureka
#          volumeMounts:
#            - name: wordpress-persistent-storage
#              mountPath: /var/www/html
#      volumes:
#        - name: wordpress-persistent-storage
#          persistentVolumeClaim:
#            claimName: wp-pv-claim